@url = http://localhost:5000/Documents
@documentId = 7D3F4242-C899-4A2F-9026-B083C523A105
#@documentId = {{$guid}}


### Get document
GET {{url}}/{{documentId}} HTTP/1.1

### Add document
POST {{url}} HTTP/1.1
Accept: application/json
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="documentId"

{{documentId}}
--MyBoundary
Content-Disposition: form-data; name="file"; filename="readme.md"

< ..\..\..\readme.md
--MyBoundary--